import type { RadarEvent } from './types'

export const RADAR_EVENTS: RadarEvent[] = [
  { id: 1,  name: 'Bitcoin Pizza Day',        sub: 'First real-world Bitcoin transaction anniversary',      date: '2026-05-22', cat: 'web3',     pri: 'high',   score: 8, audience: 'Crypto native, retail traders, Web3 community',             geo: 'Global' },
  { id: 2,  name: 'Monaco Grand Prix',        sub: 'F1 · most prestigious race in motorsport',             date: '2026-05-25', cat: 'sports',   pri: 'high',   score: 9, audience: 'M25-45, HNW, luxury enthusiasts, motorsport fans',           geo: 'Global' },
  { id: 3,  name: 'Champions League Final',   sub: 'UEFA 2026 · peak European football moment',            date: '2026-05-30', cat: 'sports',   pri: 'high',   score: 8, audience: 'M18-45, EU football fans, mainstream sports',                geo: 'Europe' },
  { id: 4,  name: 'ECB Rate Decision',        sub: 'Eurozone monetary policy announcement',                date: '2026-06-05', cat: 'business', pri: 'medium', score: 6, audience: 'Investors, traders, financial media, EU market',             geo: 'EU' },
  { id: 5,  name: 'Canadian Grand Prix',      sub: 'F1 · Montreal Circuit Gilles Villeneuve',              date: '2026-06-08', cat: 'sports',   pri: 'medium', score: 7, audience: 'F1 fans, motorsport, North America crossover',               geo: 'Global' },
  { id: 6,  name: 'Consensus 2026',           sub: 'Largest global blockchain & crypto conference',        date: '2026-06-12', cat: 'web3',     pri: 'high',   score: 9, audience: 'Crypto investors, builders, media, institutional',            geo: 'Global / US' },
  { id: 7,  name: 'Cannes Lions Festival',    sub: 'International Festival of Creativity',                 date: '2026-06-17', cat: 'business', pri: 'medium', score: 5, audience: 'Marketing leaders, brand decision-makers, media',            geo: 'France / Global' },
  { id: 8,  name: 'Nürburgring 24 Hours',     sub: 'Verstappen factor · first sellout in 50 years',       date: '2026-06-21', cat: 'sports',   pri: 'high',   score: 9, audience: 'F1 fans, EU motorsport, M18-45, tech-savvy sports fans',      geo: 'EU / Germany' },
  { id: 9,  name: 'Wimbledon',                sub: 'Grand Slam tennis · 2-week media window',              date: '2026-06-29', cat: 'sports',   pri: 'high',   score: 7, audience: 'M/F 25-50, luxury, UK/EU, premium lifestyle',                geo: 'UK / Global' },
  { id: 10, name: 'Tour de France',           sub: 'Cycling · 3-week EU-wide media spectacle',            date: '2026-07-04', cat: 'sports',   pri: 'medium', score: 6, audience: 'EU sports fans, endurance, M30-55',                          geo: 'EU / France' },
  { id: 11, name: 'British Grand Prix',       sub: 'F1 · Silverstone · home race energy',                 date: '2026-07-06', cat: 'sports',   pri: 'high',   score: 8, audience: 'F1 global fanbase, UK/EU, M18-45',                           geo: 'UK / Global' },
  { id: 12, name: 'Bastille Day',             sub: 'French national holiday · EU cultural moment',        date: '2026-07-14', cat: 'cultural', pri: 'low',    score: 3, audience: 'French market, Southern EU',                                 geo: 'France / EU' },
  { id: 13, name: 'Bitcoin Amsterdam 2026',   sub: 'Premier EU crypto conference',                        date: '2026-07-18', cat: 'web3',     pri: 'high',   score: 9, audience: 'EU crypto investors, traders, institutional, retail',         geo: 'EU / Netherlands' },
  { id: 14, name: 'Hungarian Grand Prix',     sub: 'F1 · Budapest · pre-summer break',                    date: '2026-07-20', cat: 'sports',   pri: 'medium', score: 7, audience: 'F1 fans, Central EU sports market',                          geo: 'EU / Hungary' },
  { id: 15, name: 'ECB Rate Decision',        sub: 'Summer monetary policy update',                       date: '2026-07-24', cat: 'business', pri: 'medium', score: 5, audience: 'Investors, traders, EU financial market',                    geo: 'EU' },
  { id: 16, name: 'Belgian Grand Prix',       sub: 'F1 · Spa-Francorchamps · fan-favorite circuit',      date: '2026-07-27', cat: 'sports',   pri: 'medium', score: 7, audience: 'F1 global fans, EU motorsport',                              geo: 'EU / Belgium' },
  { id: 17, name: 'Ethereum Anniversary',     sub: 'ETH Frontier mainnet · 11 years on July 30',         date: '2026-07-30', cat: 'web3',     pri: 'high',   score: 8, audience: 'Ethereum ecosystem, DeFi, builders, Web3',                   geo: 'Global' },
  { id: 18, name: 'Dutch Grand Prix',         sub: 'F1 · Zandvoort · Verstappen home race',               date: '2026-08-03', cat: 'sports',   pri: 'medium', score: 7, audience: 'F1 global fans, Dutch & EU market',                         geo: 'EU / Netherlands' },
  { id: 19, name: 'EthCC Conference 2026',    sub: 'Ethereum Community Conference · EU edition',          date: '2026-08-09', cat: 'web3',     pri: 'high',   score: 8, audience: 'EU Ethereum devs, DeFi, protocol builders',                  geo: 'EU' },
  { id: 20, name: 'Assumption Day (EU)',       sub: 'EU public holiday · reduced business activity',      date: '2026-08-15', cat: 'cultural', pri: 'low',    score: 2, audience: 'Southern EU markets, general cultural',                      geo: 'EU' },
]
